services:

  django-app:
    build: .
    image: erfaw/digital-business-card-django:v0.20.0
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - static:/app/static
    restart: unless-stopped
    # TODO (HIGH) implement depends_on to database \w condition service_healthy
    # depends_on:
    #   db:
    #     condition: service_healthy

  database:
    image: postgres:18

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # TODO (HIGH) implement service_healthy check
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U myapp -d myapp"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s

    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80" # HOST_PORT:CONTAINER_PORT
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static:ro
    depends_on:
      - django-app

volumes:
  postgres_data:
  static:
