# Generated by Django 6.0.7 on 2026-07-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo_sub', models.CharField(max_length=50)),
                ('tag_behind', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('website_preview', models.CharField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('linkedin_preview', models.CharField(blank=True)),
                ('location', models.CharField(blank=True)),
                ('response_time', models.CharField(blank=True)),
            ],
        ),
    ]
