# Generated by Django 6.0.7 on 2026-08-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
