# Generated by Django 6.0.7 on 2026-07-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='mobile_number',
        ),
    ]
